name: 'job_market_analytics'
version: '1.0.0'
config-version: 2

profile: 'job_market_analytics'

model-paths: ["models"]
test-paths: ["tests"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  job_market_analytics:
    staging:
      +materialized: view
      +schema: staging
    history:
      +schema: history
    intermediate:
      +materialized: view
      +schema: intermediate
    marts:
      jobs:
        +materialized: table
        +schema: marts